# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Site settings
author: 'Giulia'
favicon: /img/favicon.png
avatar: /img/avatar.jpg
author_bio: 'Your biography can be written here.'
title: Semantic Noodles
email: giulia.osti@ucdconnect.ie
since: 2023 # Copyright

# Top Menu
menu:
  Publications: /#Publications
  About: /
  Blog: https://phower.me

# Page Background
loading_bg:
  flink: /img/profile.png

# Social Links
social:
  enable: true
  social_links:
    fab fa-twitter: /
    fab fa-facebook-square: /
    fab fa-github: /
    fab fa-linkedin: /
    fas fa-envelope: / # E-mail
    fas fa-rss: /  # RSS

# Additional Social Links
e_social:
  enable: true
  e_social_links:
    Google Scholar: / || fas fa-graduation-cap
    ORCID: / || fab fa-orcid

# CV download link
cv_dl:
  enable: true
  dir: /attaches/CV.pdf
  description: My Detailed CV

# Box-shadow
box_shadow:
  enable: false

# CDN
CDN_USE:
  css:
    - /css/index.css
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # FontAwesome 5
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - /js/main.js

# Site Description
# description: >-
#   This is Giulia, a D-Real-funded PhD candidate based at the University College Dublin,
#   School of Information and Communication Studies.

# Site URLs
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://semanticnoodles.github.io" # the base hostname & protocol for your site, e.g., http://example.com

# Declare theme
theme: Academia

# Build settings
plugins:
  - jekyll-feed

# Redirects
redirects:
  - from: /conferences/2023/09/03/ASIST-Poster.html
    to: /asist2023/

# Exclude from processing
# The following items will not be processed by default
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
