# site settings
title: Semantic Noodles
subtitle: Giulia Osti
email: giulia.osti@ucdconnect.ie
description: This is Giulia, a <a href="https://d-real.ie/" target="_blank">d-real/SFI-funded</a> PhD candidate based at the University College Dublin, <a href="https://www.ucd.ie/ics/" target="_blank">School of Information and Communication Studies</a>.
baseurl: # the subpath of your site, e.g. /blog
url: https://semanticnoodles.github.io # the base hostname & protocol for your site
author: Giulia Osti

#street_address: 1234 Somewhere Road
#city: Nashville
#state: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: log # accepts "log" or "pages"
tiles-count: 2

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/semanticnoodles
  LinkedIn: https://www.linkedin.com/in/godigitalcorner/ 
  Twitter: http://www.twitter.com/semanticnoodles
# Will add more

# build settings
markdown: kramdown
sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- "*.DS_Store"

# Fetch posts from log
collections:
  log:
    output: true
